/**
 * Assign-to-agent run options → CLI arguments, per provider. Pure (no vscode)
 * so the flag mapping and session-mode logic are unit-testable from out/.
 *
 * Session modes:
 *   fresh    — new session, id pre-assigned (--session-id) so MCP writes are stamped
 *   continue — resume the thread's last agent session (multi-turn follow-ups)
 *   fork     — fork a mentioned session (@claude:<sid>) at its tip
 *   auto     — fork if mentioned, else continue if the thread has a session, else fresh
 */

export interface RunOptions {
  model?: string;
  permissionMode?: 'default' | 'acceptEdits' | 'plan' | 'bypassPermissions';
  /** Reasoning effort (--effort). The ⚙ menu probes CLI support; programmatic values always pass through. */
  effort?: string;
  /** Tool allowlist for the run; defaults to the comments MCP toolset. */
  allowedTools?: string[];
  /** Replaces the base system prompt (--system-prompt). Agent definition and append text still stack on top. */
  replaceSystemPrompt?: string;
  /** Appended to the agent-definition prompt (if any). */
  appendSystemPrompt?: string;
  maxTurns?: number;
  /** Escape hatch for flags without first-class support (betas, future flags, …). */
  extraArgs?: string[];
  sessionMode?: 'auto' | 'fresh' | 'continue' | 'fork';
}

export const DEFAULT_MCP_TOOLS = [
  'mcp__comments__list_threads',
  'mcp__comments__get_thread',
  'mcp__comments__reply_to_thread',
  'mcp__comments__resolve_thread',
  'mcp__comments__attach_suggestion',
  'mcp__comments__set_severity',
  'mcp__comments__re_anchor_thread',
];

export interface BuiltRun {
  args: string[];
  sessionMode: 'fresh' | 'continue' | 'fork';
  /** Session id knowable before the run (fresh: preset; continue: resumed). */
  knownSessionId?: string;
}

export function buildAgentArgs(params: {
  prompt: string;
  mcpConfigJson: string;
  options: RunOptions;
  agentSystemPrompt?: string;
  mentionSessionId?: string;
  threadLastSessionId?: string;
  /** Fresh-run session id, generated by the caller. */
  newSessionId: string;
}): BuiltRun {
  const { options } = params;
  const requested = options.sessionMode ?? 'auto';
  const sessionMode: BuiltRun['sessionMode'] =
    requested === 'auto'
      ? params.mentionSessionId
        ? 'fork'
        : params.threadLastSessionId
          ? 'continue'
          : 'fresh'
      : requested === 'fork' && !params.mentionSessionId && !params.threadLastSessionId
        ? 'fresh' // nothing to fork
        : requested === 'continue' && !params.threadLastSessionId
          ? 'fresh' // nothing to continue
          : requested;

  const args = [
    '-p', params.prompt,
    '--output-format', 'stream-json', '--verbose',
    '--mcp-config', params.mcpConfigJson,
    '--allowedTools', (options.allowedTools?.length ? options.allowedTools : DEFAULT_MCP_TOOLS).join(','),
  ];

  let knownSessionId: string | undefined;
  if (sessionMode === 'fresh') {
    knownSessionId = params.newSessionId;
    args.push('--session-id', params.newSessionId);
  } else if (sessionMode === 'continue') {
    knownSessionId = params.threadLastSessionId!;
    args.push('--resume', params.threadLastSessionId!);
  } else {
    args.push('--resume', (params.mentionSessionId ?? params.threadLastSessionId)!, '--fork-session');
  }

  if (options.model) args.push('--model', options.model);
  if (options.effort) args.push('--effort', options.effort);
  if (options.permissionMode && options.permissionMode !== 'default') {
    args.push('--permission-mode', options.permissionMode);
  }
  if (options.maxTurns && options.maxTurns > 0) args.push('--max-turns', String(options.maxTurns));

  if (options.replaceSystemPrompt) args.push('--system-prompt', options.replaceSystemPrompt);
  const appended = [params.agentSystemPrompt, options.appendSystemPrompt].filter(Boolean).join('\n\n');
  if (appended) args.push('--append-system-prompt', appended);

  if (options.extraArgs?.length) args.push(...options.extraArgs);
  return { args, sessionMode, knownSessionId };
}

/**
 * Codex flag mapping. Deliberately a separate builder rather than a table of
 * per-provider flag names: the two CLIs differ in shape, not just spelling.
 *
 * The differences that matter:
 *  - No `--session-id`: a Codex session id cannot be pre-assigned, so a fresh
 *    run's id is only knowable by reading it back off the `--json` stream
 *    (hence knownSessionId is undefined for `fresh`, and the caller must watch
 *    the stream). Claude's flow pre-assigns it so MCP writes are stamped.
 *  - No `--allowedTools`: tool access is governed by the sandbox policy.
 *  - No system-prompt flags: an agent definition's prompt is prepended to the
 *    user prompt instead.
 *  - MCP servers are configured through `-c mcp_servers.<name>.…` overrides
 *    rather than a config-file flag.
 *  - `codex exec resume` has a REDUCED option set: no `--sandbox`, `-C/--cd`,
 *    `--add-dir`, or `--profile`. Passing `--sandbox` to it is a hard argument
 *    -parse error, so the sandbox policy goes through `-c sandbox_mode=…`,
 *    which is valid on both subcommands. Verified against codex-cli 0.146.1;
 *    tests/agentargs.test.js pins the resume-safe flag set.
 */
export function buildCodexArgs(params: {
  prompt: string;
  /** Absolute path to bin/mcp-comments.js — wired in as the `comments` server. */
  mcpServerPath?: string;
  options: RunOptions;
  agentSystemPrompt?: string;
  mentionSessionId?: string;
  threadLastSessionId?: string;
}): BuiltRun {
  const { options } = params;
  const requested = options.sessionMode ?? 'auto';
  const sessionMode: BuiltRun['sessionMode'] =
    requested === 'auto'
      ? params.mentionSessionId
        ? 'fork'
        : params.threadLastSessionId
          ? 'continue'
          : 'fresh'
      : requested === 'fork' && !params.mentionSessionId && !params.threadLastSessionId
        ? 'fresh'
        : requested === 'continue' && !params.threadLastSessionId
          ? 'fresh'
          : requested;

  // Codex has no fork primitive in `exec`; resuming a mentioned session is the
  // closest equivalent, so fork and continue produce the same invocation.
  const resumeTarget =
    sessionMode === 'fork'
      ? (params.mentionSessionId ?? params.threadLastSessionId)
      : sessionMode === 'continue'
        ? params.threadLastSessionId
        : undefined;

  const args = ['exec'];
  if (resumeTarget) args.push('resume', resumeTarget);
  args.push('--json', '--skip-git-repo-check');

  if (params.mcpServerPath) {
    args.push('-c', 'mcp_servers.comments.command="node"');
    args.push('-c', `mcp_servers.comments.args=["${params.mcpServerPath}"]`);
  }
  if (options.model) args.push('--model', options.model);
  // Reasoning effort and sandbox policy are config overrides, not flags: `-c`
  // is accepted by both `exec` and `exec resume`, while `--sandbox` is not.
  if (options.effort) args.push('-c', `model_reasoning_effort="${options.effort}"`);
  args.push('-c', `sandbox_mode="${codexSandbox(options.permissionMode)}"`);

  if (options.extraArgs?.length) args.push(...options.extraArgs);

  // Prompt last (positional). System-prompt text has nowhere else to go.
  const preamble = [options.replaceSystemPrompt, params.agentSystemPrompt, options.appendSystemPrompt]
    .filter(Boolean)
    .join('\n\n');
  args.push(preamble ? `${preamble}\n\n---\n\n${params.prompt}` : params.prompt);

  return { args, sessionMode, knownSessionId: resumeTarget };
}

function codexSandbox(mode: RunOptions['permissionMode']): string {
  switch (mode) {
    case 'plan':
      return 'read-only';
    case 'bypassPermissions':
      return 'danger-full-access';
    case 'acceptEdits':
    case 'default':
    default:
      return 'workspace-write';
  }
}

/**
 * Extract the session id Codex reports on its `--json` event stream.
 *
 * The id arrives on the FIRST line as `{"type":"thread.started","thread_id":…}`
 * — before the model has produced anything, and therefore before any MCP write
 * could happen. That ordering is what makes late-bound session stamping work.
 *
 * `thread_id` is the same id the rollout filename and `session_meta.session_id`
 * use, so it is directly resolvable by the codex provider. The other shapes are
 * accepted defensively across codex-cli versions.
 */
export function codexSessionIdFromEvent(line: string): string | undefined {
  try {
    const obj = JSON.parse(line);
    const id =
      obj?.thread_id ?? obj?.session_id ?? obj?.payload?.session_id ?? obj?.payload?.id;
    return typeof id === 'string' && /^[0-9a-fA-F-]{36}$/.test(id) ? id : undefined;
  } catch {
    return undefined;
  }
}

/** The thread's most recent agent session (latest event stamped with one). */
export function lastSessionId(events: Array<{ actor?: { session?: string } }>): string | undefined {
  for (let i = events.length - 1; i >= 0; i--) {
    const s = events[i].actor?.session;
    if (s) return s;
  }
  return undefined;
}
